version: '3.8'
services:
  saf-core:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: travisrvigue-design/saf-titancore:local
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app:ro
